### ISSUE TITLE
Add new tracks in pyGenomeTracks installed by conda

### ISSUE THREAD

**Issue by YichaoCaiDBS** [deeptools/pyGenomeTracks#190]
Hi,

Thanks for developing this tool for genome visualization. I have been looking for a solution to plot genome tracks in python for a long long time.

I am trying to add some new tracks into pyGenomeTrack that is installed using conda.
Version information:
```
pyGenomeTracks    3.2.1     py_0    bioconda
conda    4.7.12    py36_0    conda-forge
python    3.6.7    h381d211_1004    conda-forge
```
I am trying to add a new track class to pygenometracks as described in: https://github.com/deeptools/pyGenomeTracks/blob/master/docs/Creating_new_tracks.md

The new track I try to add in is the example of `TextTrack` in the document. After I copied the `TextTrack.py` to the same folder as all of the track classes and using the same testing .ini file, I got an error of unrecognized track type.
 

The error I got:
```
Traceback (most recent call last):
  File "/home/yichao/anaconda3/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "/home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/plotTracks.py", line 272, in main
    trp = PlotTracks(args.tracks.name, args.width, fig_height=args.height, fontsize=args.fontSize, dpi=args.dpi, track_label_width=args.trackLabelFraction)
  File "/home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracksClass.py", line 78, in __init__
    self.parse_tracks(tracks_file)
  File "/home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracksClass.py", line 383, in parse_tracks
    self.available_tracks.keys()))
pygenometracks.utilities.InputError: Section 2. [new track]: the file_type text does not exists.
possible file_type are:dict_keys(['bed', 'bedgraph', 'sushi_links', 'bigwig', 'hic_matrix', 'links', 'hlines', None, 'bedgraph_matrix', 'epilogos', 'narrow_peak', 'domains']).
```

It seems that the newly added `TextTrack.py` is not recognized by pyGenomeTrack. How should I do to make this new track work properly? 
Also, I am curious about the file_type of 'sushi_links' because I can not find any hits about sushi in the github repo.

Thank you!

**Comment by lldelisle** [comment]
Hi,
I am very happy that you like pyGenomeTracks. I am sorry, I cannot reproduce your bug.
Here is what I did:
```
# Create a new conda environment to test with the same versions
conda create -n pgt_newtrack pygenometracks=3.2.1 python=3.6.7
# activate the new environment
conda activate pgt_newtrack
```
First I created the ini file as in https://github.com/deeptools/pyGenomeTracks/blob/master/docs/Creating_new_tracks.md

When I ran 
```
pgt --tracks new_track.ini --region X:3000000-3200000 -o new_track.png
```
I got an error like you except the last line:
```
pygenometracks.utilities.InputError: Section 2. [new track]: the file_type text does not exists.
possible file_type are:dict_keys(['bedgraph', 'links', 'hlines', 'bed', 'hic_matrix', 'bigwig', None, 'domains', 'bedgraph_matrix', 'narrow_peak', 'epilogos']).
```
I do not have any `sushi_links` here. Are you sure it is not a new track you created?

Then in the folder that would be for you `/home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks/` I put a new file which included what is [here](https://github.com/deeptools/pyGenomeTracks/blob/master/docs/Creating_new_tracks.md) but I needed to add at the beginning:
```
from . GenomeTrack import GenomeTrack
import numpy as np
```
Then it worked perfectly.

However, rather than directly modifying the lib dir of the conda environment I would recommend to clone the repository, add your new track in the folder tracks and then from the git directory run `python setup.py install`.

I hope this can help in a way. If you are still stuck, please do not hesitate to reply.

**Comment by YichaoCaiDBS** [comment]
Hi! Thanks for your reply!

For the `sushi_link` type, I think I have some left-over script for new tracks I defined in my last installation. 

Following your instruction:
1. I have re-installed pyGenomeTracks from conda, as well as cloned this git repo.
2. Put this new track file under the git repo under `pygenometracks/tracks/`.
```
from . GenomeTrack import GenomeTrack
import numpy as np


class TextTrack(GenomeTrack):
    SUPPORTED_ENDINGS = ['.txt']  # this is used by make_tracks_file to guess the type of track based on file name
    TRACK_TYPE = 'text'
    OPTIONS_TXT = """
height = 3
title =
text =
# x position of text in the plot (in bp)
x position =
"""
    DEFAULTS_PROPERTIES = {'text': 'hello world'}
    NECESSARY_PROPERTIES = ['x_position']
    SYNONYMOUS_PROPERTIES = {}
    POSSIBLE_PROPERTIES = {}
    BOOLEAN_PROPERTIES = []
    STRING_PROPERTIES = ['text', 'title', 'file_type']
    FLOAT_PROPERTIES = {'height': [0, np.inf],
                        'x_position': [0, np.inf]}
    INTEGER_PROPERTIES = {}
    def plot(self, ax, chrom, region_start, region_end):
        """
        This example simply plots the given title at a fixed
        location in the axis. The chrom, region_start and region_end
        variables are not used.
        Args:
            ax: matplotlib axis to plot
            chrom_region: chromosome name
            start_region: start coordinate of genomic position
            end_region: end coordinate
        """
        # print text at position x = self.properties['x position'] and y = 0.5 (center of the plot)
        ax.text(self.properties['x_position'], 0.5, self.properties['text'])
```
3. Run the `python setup.py install` in the git repo. I can get this screen print:
```
running install
running build
running build_py
copying pygenometracks/tracks/TextTracks.py -> build/lib/pygenometracks/tracks
running egg_info
writing pyGenomeTracks.egg-info/PKG-INFO
writing dependency_links to pyGenomeTracks.egg-info/dependency_links.txt
writing requirements to pyGenomeTracks.egg-info/requires.txt
writing top-level names to pyGenomeTracks.egg-info/top_level.txt
reading manifest file 'pyGenomeTracks.egg-info/SOURCES.txt'
writing manifest file 'pyGenomeTracks.egg-info/SOURCES.txt'
running build_scripts
running install_lib
copying build/lib/pygenometracks/getAllDefaultsAndPossible.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks
copying build/lib/pygenometracks/__init__.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks
copying build/lib/pygenometracks/tracks/TextTracks.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks
copying build/lib/pygenometracks/tracks/TADsTrack.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks
copying build/lib/pygenometracks/tracks/__init__.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks
copying build/lib/pygenometracks/tracks/BedGraphMatrixTrack.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks
copying build/lib/pygenometracks/tracks/BedGraphTrack.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks
copying build/lib/pygenometracks/tracks/BigWigTrack.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks
copying build/lib/pygenometracks/tracks/HiCMatrixTrack.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks
copying build/lib/pygenometracks/tracks/LinksTrack.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks
copying build/lib/pygenometracks/tracks/GenomeTrack.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks
copying build/lib/pygenometracks/tracks/BedTrack.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks
copying build/lib/pygenometracks/tracks/HLinesTrack.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks
copying build/lib/pygenometracks/tracks/EpilogosTrack.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks
copying build/lib/pygenometracks/tracks/NarrowPeakTrack.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks
copying build/lib/pygenometracks/makeTracksFile.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks
copying build/lib/pygenometracks/_version.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks
copying build/lib/pygenometracks/utilities.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks
copying build/lib/pygenometracks/readBed.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks
copying build/lib/pygenometracks/tracksClass.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks
copying build/lib/pygenometracks/plotTracks.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks
copying build/lib/pygenometracks/readGtf.py -> /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks/TextTracks.py to TextTracks.cpython-36.pyc
running install_egg_info
Copying pyGenomeTracks.egg-info to /home/yichao/anaconda3/lib/python3.6/site-packages/pyGenomeTracks-3.2-py3.6.egg-info
running install_scripts
changing mode of /home/yichao/anaconda3/bin/pgt to 775
changing mode of /home/yichao/anaconda3/bin/pyGenomeTracks to 775
changing mode of /home/yichao/anaconda3/bin/make_tracks_file to 775
```
4. I tried again the `pgt --tracks new_track.ini --region X:3000000-3200000 -o new_track.png`, and get this same error:
```
Traceback (most recent call last):
  File "/home/yichao/anaconda3/bin/pgt", line 11, in <module>
    main(args)
  File "/home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/plotTracks.py", line 272, in main
    trp = PlotTracks(args.tracks.name, args.width, fig_height=args.height, fontsize=args.fontSize, dpi=args.dpi, track_label_width=args.trackLabelFraction)
  File "/home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracksClass.py", line 78, in __init__
    self.parse_tracks(tracks_file)
  File "/home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracksClass.py", line 383, in parse_tracks
    self.available_tracks.keys()))
pygenometracks.utilities.InputError: Section 2. [new track]: the file_type text does not exists.
possible file_type are:dict_keys(['bed', 'bedgraph', 'bigwig', 'hic_matrix', 'links', 'hlines', None, 'bedgraph_matrix', 'epilogos', 'narrow_peak', 'domains']).
```
In the package directory of conda, the `TextTracks.py` is under the same directory as other track files.
Still, I can not get the new track to work. Did I do anything wrong? 

I noticed that after running `python setyup.py install` the package information listed by conda changed to: `genometracks            3.2                      pypi_0    pypi`. Is this what to expect?


Thanks!

**Comment by lldelisle** [comment]
Hi,
Could you try to remove the `.pyc` files? They are in `/home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/__pycache__/`?

**Comment by YichaoCaiDBS** [comment]
Hi,

I tried removing all the `*.pyc` files under `/home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/__pycache__/` and `/home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks/__pycache__/`.

After that, I ran `python setup.py install` and get screen print of these:
```
running install
running build
running build_py
running egg_info
writing pyGenomeTracks.egg-info/PKG-INFO
writing dependency_links to pyGenomeTracks.egg-info/dependency_links.txt
writing requirements to pyGenomeTracks.egg-info/requires.txt
writing top-level names to pyGenomeTracks.egg-info/top_level.txt
reading manifest file 'pyGenomeTracks.egg-info/SOURCES.txt'
writing manifest file 'pyGenomeTracks.egg-info/SOURCES.txt'
running build_scripts
running install_lib
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/getAllDefaultsAndPossible.py to getAllDefaultsAndPossible.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/__init__.py to __init__.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks/TextTracks.py to TextTracks.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks/TADsTrack.py to TADsTrack.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks/__init__.py to __init__.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks/BedGraphMatrixTrack.py to BedGraphMatrixTrack.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks/BedGraphTrack.py to BedGraphTrack.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks/BigWigTrack.py to BigWigTrack.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks/HiCMatrixTrack.py to HiCMatrixTrack.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks/LinksTrack.py to LinksTrack.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks/GenomeTrack.py to GenomeTrack.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks/BedTrack.py to BedTrack.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks/HLinesTrack.py to HLinesTrack.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks/EpilogosTrack.py to EpilogosTrack.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracks/NarrowPeakTrack.py to NarrowPeakTrack.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/makeTracksFile.py to makeTracksFile.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/_version.py to _version.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/utilities.py to utilities.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/readBed.py to readBed.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracksClass.py to tracksClass.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/plotTracks.py to plotTracks.cpython-36.pyc
byte-compiling /home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/readGtf.py to readGtf.cpython-36.pyc
running install_egg_info
removing '/home/yichao/anaconda3/lib/python3.6/site-packages/pyGenomeTracks-3.2-py3.6.egg-info' (and everything under it)
Copying pyGenomeTracks.egg-info to /home/yichao/anaconda3/lib/python3.6/site-packages/pyGenomeTracks-3.2-py3.6.egg-info
running install_scripts
changing mode of /home/yichao/anaconda3/bin/pgt to 775
changing mode of /home/yichao/anaconda3/bin/pyGenomeTracks to 775
changing mode of /home/yichao/anaconda3/bin/make_tracks_file to 775
```
However, I am still getting the same error:
```
Traceback (most recent call last):
  File "/home/yichao/anaconda3/bin/pgt", line 11, in <module>
    main(args)
  File "/home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/plotTracks.py", line 272, in main
    trp = PlotTracks(args.tracks.name, args.width, fig_height=args.height, fontsize=args.fontSize, dpi=args.dpi, track_label_width=args.trackLabelFraction)
  File "/home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracksClass.py", line 78, in __init__
    self.parse_tracks(tracks_file)
  File "/home/yichao/anaconda3/lib/python3.6/site-packages/pygenometracks/tracksClass.py", line 383, in parse_tracks
    self.available_tracks.keys()))
pygenometracks.utilities.InputError: Section 2. [new track]: the file_type text does not exists.
possible file_type are:dict_keys(['bed', 'bedgraph', 'bigwig', 'hic_matrix', 'links', 'hlines', None, 'bedgraph_matrix', 'epilogos', 'narrow_peak', 'domains']).
```

**Comment by lldelisle** [comment]
Ah... The difference I see is that you called your new track `TextTracks.py` instead of `TextTrack.py`. For the moment I cannot tell you where this is important but I think it will solve. Please, tell me.

**Comment by YichaoCaiDBS** [comment]
Hi I just spot this trunk of code in the `__init__.py` in the track folder:
```
for py in [f[:-3] for f in os.listdir(path) if f.endswith('Track.py') and f != '__init__.py']:
    mod = __import__('.'.join([__name__, py]), fromlist=[py])
    classes = [getattr(mod, x) for x in dir(mod) if isinstance(getattr(mod, x), type)]
    for cls in classes:
        setattr(sys.modules[__name__], cls.__name__, cls)
```
It seems that the new track name should ended with `Track.py`. Indeed, after I change the new track name to `TextTrack.py`, everything works fine.

Thank you so much for your help! 
P.S.: Maybe it would be great to add this into the document of creating new tracks.

**Comment by lldelisle** [comment]
Yes I was about to update it.
Many thanks for reporting this issue. It helps us to improve the documentation.
