### ISSUE TITLE
Calling a bigwig file from a different directory

### ISSUE THREAD

**Issue by jakesorel** [deeptools/pyGenomeTracks#327]
**Welcome to the pyGenomeTracks GitHub repository! Before opening the issue please check
 that the following requirements are met :**

  - [x ] Search whether this issue (or a similar issue) has been solved before
  using the search tab above. Link the previous issue if appropriate below.

  - [ x] Paste your pyGenomeTracks version (`pyGenomeTracks --version`) and your python
  version (`python --version`) below.
pyGenomeTracks 3.6

Python 3.7.9

  - [x] Paste the full pyGenomeTracks command that produces the issue below
  (ignore if you simply spotted the issue in the code/documentation).

ini file: 

`[D5_500_M]
file=~/camp/lab/.../D5_500_M_R1.mLb.clN.bigWig
title=D5_500_M
color = #666
min_value = 0
#max_value = auto
height = 1.500
number of bins = 500
nans to zeros = True
show data range = yes
file_type = bigwig`

` pyGenomeTracks --tracks tracks.ini --region chr16:91191337-91193823 -o plot.pdf`

  - [ x] Paste the output printed on screen from the command that produces the issue
  below (ignore if you simply spotted the issue in the code/documentation).

Traceback (most recent call last):
  File "/camp/home/cornwaj/.conda/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/tracksClass.py", line 577, in check_file_exists
    open(file_name_to_check, 'r').close()
FileNotFoundError: [Errno 2] No such file or directory: '~/camp/lab/.../D5_500_M_R1.mLb.clN.bigWig'

(I have replaced the extended directory reference with "..."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/camp/home/cornwaj/.conda/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/tracksClass.py", line 585, in check_file_exists
    open(name_with_tracks_path_to_check, 'r').close()
FileNotFoundError: [Errno 2] No such file or directory: 'results/genome_plots/o2e33/config_files/all/~/camp/lab/.../D5_500_M_R1.mLb.clN.bigWig'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/camp/home/cornwaj/.conda/envs/pygenometracks/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "/camp/home/cornwaj/.conda/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/plotTracks.py", line 321, in main
    plot_regions=regions, plot_width=args.plotWidth)
  File "/camp/home/cornwaj/.conda/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/tracksClass.py", line 78, in __init__
    self.parse_tracks(tracks_file, plot_regions=plot_regions)
  File "/camp/home/cornwaj/.conda/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/tracksClass.py", line 512, in parse_tracks
    track_options['file_type'] == 'hic_matrix')
  File "/camp/home/cornwaj/.conda/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/tracksClass.py", line 588, in check_file_exists
    raise InputError(f"File in section [{track_dict['section_name']}] "
pygenometracks.utilities.InputError: File in section [1. [D5_500_M]] not found:
~/camp/lab/.../D5_500_M_R1.mLb.clN.bigWig

-------------

Hi there, 

I've been trying to run your software, plotting a bigwig file found in a different directory to the ini file. I have tried different ways of calling the bigwig file ("/xxx", "~/xxx") but to no avail. Please could you help me fix this referencing issue. 

Thanks so much 

Best

Jake

**Comment by lldelisle** [comment]
Hi,
For me it really seems to be linked to the `~` sign... Could you retry to put the full path?

**Comment by jakesorel** [comment]
Hi there,

I also tried without “~” but to no avail. I realise in line 583-584 of the tracksClass.py file, the file directory is appended with that of “.ini” file

[cid:image001.png@01D703A4.F1474A60]
When I remove the “tracks_path + “/”” from both of these lines, the code now runs perfectly.

Thank you for your help.

Best

Jake
