### ISSUE TITLE
Error when plotting outside of range of data for matrices

### ISSUE THREAD

**Issue by lldelisle** [deeptools/pyGenomeTracks#370]
pgt 3.6
```
$ pgt --tracks pygenometracks/tests/test_data/browser_tracks_hic.ini --region chrX:3000000-4000000 -o /tmp/test.png
WARNING:pygenometracks.tracksClass:In section 5. [tads], these parameters are unused:['show_data_range'].

WARNING:pygenometracks.tracksClass:In section 8. [test arcs], these parameters are unused:['show_data_range'].

INFO:pygenometracks.tracksClass:initialize 1. [hic matrix]
WARNING:hicmatrix.HiCMatrix:Bin size is not homogeneous.                                       Median 1889

INFO:pygenometracks.tracksClass:initialize 2. [hic matrix]
WARNING:hicmatrix.HiCMatrix:Bin size is not homogeneous.                                       Median 1889

INFO:pygenometracks.tracksClass:initialize 3. [spacer]
INFO:pygenometracks.tracksClass:initialize 4. [hic matrix]
WARNING:hicmatrix.HiCMatrix:Bin size is not homogeneous.                                       Median 1889

INFO:pygenometracks.tracksClass:initialize 5. [tads]
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 9516.57it/s]
INFO:pygenometracks.tracksClass:initialize 6. [spacer]
INFO:pygenometracks.tracksClass:initialize 7. [hic matrix]
WARNING:hicmatrix.HiCMatrix:Bin size is not homogeneous.                                       Median 1889

INFO:pygenometracks.tracksClass:initialize 8. [test arcs]
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 8991.01it/s]
INFO:pygenometracks.tracksClass:initialize 9. [test bigwig]
INFO:pygenometracks.tracksClass:initialize 10. [spacer]
INFO:pygenometracks.tracksClass:initialize 11. [hic matrix]
WARNING:hicmatrix.HiCMatrix:Bin size is not homogeneous.                                       Median 1843

INFO:pygenometracks.tracksClass:initialize 12. [spacer]
INFO:pygenometracks.tracksClass:initialize 13. [x-axis]
INFO:pygenometracks.tracksClass:time initializing track(s):
INFO:pygenometracks.tracksClass:6.316032886505127
DEBUG:pygenometracks.tracksClass:Figure size in cm is 40 x 24.69019994503326. Dpi is set to 72

INFO:pygenometracks.tracksClass:plotting 1. [hic matrix]
INFO:pygenometracks.tracks.GenomeTrack:setting min, max values for track 1. [hic matrix] to: 5.0, 212.9160803435907

INFO:pygenometracks.tracksClass:plotting 2. [hic matrix]
INFO:pygenometracks.tracks.GenomeTrack:setting min, max values for track 2. [hic matrix] to: 5.0, 70.0

INFO:pygenometracks.tracksClass:plotting 3. [spacer]
INFO:pygenometracks.tracksClass:plotting 4. [hic matrix]
INFO:pygenometracks.tracks.GenomeTrack:setting min, max values for track 4. [hic matrix] to: 10.0, 150.0

INFO:pygenometracks.tracksClass:plotting 5. [tads]
INFO:pygenometracks.tracksClass:plotting 6. [spacer]
INFO:pygenometracks.tracksClass:plotting 7. [hic matrix]
INFO:pygenometracks.tracks.GenomeTrack:setting min, max values for track 7. [hic matrix] to: 15.0, 200.0

INFO:pygenometracks.tracksClass:plotting 8. [test arcs]
DEBUG:pygenometracks.tracks.GenomeTrack:2 were links plotted
INFO:pygenometracks.tracksClass:plotting 9. [test bigwig]
INFO:pygenometracks.tracksClass:plotting 10. [spacer]
INFO:pygenometracks.tracksClass:plotting 11. [hic matrix]
INFO:pygenometracks.tracks.GenomeTrack:setting min, max values for track 11. [hic matrix] to: 0.0, 150.0

INFO:pygenometracks.tracksClass:plotting 12. [spacer]
INFO:pygenometracks.tracksClass:plotting 13. [x-axis]
(pgt_3.6) [ldelisle@SV-49-002 wetransfer_pygenometracks-input-files_2022-01-13_1534]$ pgt --tracks ~/Documents/mygit/pyGenomeTracks/pygenometracks/tests/test_data/browser_tracks_hic.ini --region chrX:30000000-31000000 -o /tmp/test.png
WARNING:pygenometracks.tracksClass:In section 5. [tads], these parameters are unused:['show_data_range'].

WARNING:pygenometracks.tracksClass:In section 8. [test arcs], these parameters are unused:['show_data_range'].

INFO:pygenometracks.tracksClass:initialize 1. [hic matrix]
WARNING:hicmatrix.HiCMatrix:Bin size is not homogeneous.                                       Median 1889

INFO:pygenometracks.tracksClass:initialize 2. [hic matrix]
WARNING:hicmatrix.HiCMatrix:Bin size is not homogeneous.                                       Median 1889

INFO:pygenometracks.tracksClass:initialize 3. [spacer]
INFO:pygenometracks.tracksClass:initialize 4. [hic matrix]
WARNING:hicmatrix.HiCMatrix:Bin size is not homogeneous.                                       Median 1889

INFO:pygenometracks.tracksClass:initialize 5. [tads]
0it [00:00, ?it/s]
WARNING:pygenometracks.tracks.GenomeTrack:No valid intervals were found in file /home/ldelisle/Documents/mygit/pyGenomeTracks/pygenometracks/tests/test_data/tad_classification.bed.

INFO:pygenometracks.tracksClass:initialize 6. [spacer]
INFO:pygenometracks.tracksClass:initialize 7. [hic matrix]
WARNING:hicmatrix.HiCMatrix:Bin size is not homogeneous.                                       Median 1889

INFO:pygenometracks.tracksClass:initialize 8. [test arcs]
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 9098.27it/s]
INFO:pygenometracks.tracksClass:initialize 9. [test bigwig]
INFO:pygenometracks.tracksClass:initialize 10. [spacer]
INFO:pygenometracks.tracksClass:initialize 11. [hic matrix]
WARNING:hicmatrix.HiCMatrix:Bin size is not homogeneous.                                       Median 1843

INFO:pygenometracks.tracksClass:initialize 12. [spacer]
INFO:pygenometracks.tracksClass:initialize 13. [x-axis]
INFO:pygenometracks.tracksClass:time initializing track(s):
INFO:pygenometracks.tracksClass:6.3877222537994385
DEBUG:pygenometracks.tracksClass:Figure size in cm is 40 x 24.69019994503326. Dpi is set to 72

INFO:pygenometracks.tracksClass:plotting 1. [hic matrix]
WARNING:pygenometracks.tracks.GenomeTrack:*Warning*
The region to plot extends beyond the chromosome size. Please check.
X size: 22422827. Region to plot 30000000-31000000

Traceback (most recent call last):
  File "/home/ldelisle/.conda/envs/pgt_3.6/bin/pgt", line 11, in <module>
    main(args)
  File "/home/ldelisle/.conda/envs/pgt_3.6/lib/python3.6/site-packages/pygenometracks/plotTracks.py", line 341, in main
    decreasing_x_axis=args.decreasingXAxis)
  File "/home/ldelisle/.conda/envs/pgt_3.6/lib/python3.6/site-packages/pygenometracks/tracksClass.py", line 272, in plot
    track.plot(plot_axis, chrom, start, end)
  File "/home/ldelisle/.conda/envs/pgt_3.6/lib/python3.6/site-packages/pygenometracks/tracks/HiCMatrixTrack.py", line 269, in plot
    enumerate(self.hic_ma.cut_intervals)
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by lldelisle** [comment]
Solved in version 3.7
