### ISSUE TITLE
AttributeError: 'BigWigTrack' object has no attribute 'bw2'

### ISSUE THREAD

**Issue by matteozoia4** [deeptools/pyGenomeTracks#378]
**Dear Lucille,**

**working with some .bigWig files I receive the following error:**

pyGenomeTracks  --tracks CTCF_ESC_FL-HL.ini --region chr3:65996079-67396078 --trackLabelFraction 0.2 --width 38 --dpi 300 -o CTCF_ESC_FL-HL.png
INFO:pygenometracks.tracksClass:initialize 1. [x-axis]
INFO:pygenometracks.tracksClass:initialize 2. [spacer]
INFO:pygenometracks.tracksClass:initialize 3. [spacer]
INFO:pygenometracks.tracksClass:initialize 4. [ChIP_ES_Intersect_peaks]
100%|████████████████████████████████████████| 36/36 [00:00<00:00, 21738.40it/s]
INFO:pygenometracks.tracksClass:initialize 5. [ChIP_ES_CTCF_rep1]
[bwHdrRead] There was an error while reading in the header!
[pyBwOpen] bw is NULL!
Traceback (most recent call last):
  File "/Users/mz20v137/opt/anaconda3/envs/pygenometracks/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "/Users/mz20v137/opt/anaconda3/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/plotTracks.py", line 321, in main
    plot_regions=regions, plot_width=args.plotWidth)
  File "/Users/mz20v137/opt/anaconda3/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/tracksClass.py", line 109, in __init__
    self.track_obj_list.append(track_class(properties))
  File "/Users/mz20v137/opt/anaconda3/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/tracks/BigWigTrack.py", line 116, in __init__
    self.bw = pyBigWig.open(self.properties['file'])
RuntimeError: Received an error during file opening!
Exception ignored in: <function BigWigTrack.__del__ at 0x7f8fa3a6b5f0>
Traceback (most recent call last):
  File "/Users/mz20v137/opt/anaconda3/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/tracks/BigWigTrack.py", line 287, in __del__
    if self.bw2 is not None:
AttributeError: 'BigWigTrack' object has no attribute 'bw2'

**pyGenomeTracks 3.6**

**What could be the issue? Wrong .bw format?**

**Best regards,**

**Matteo Zoia**

**Comment by lldelisle** [comment]
Hi,
The error is in fact above:
```
[bwHdrRead] There was an error while reading in the header!
[pyBwOpen] bw is NULL!
```

**Comment by lldelisle** [comment]
Closing the issue: after personal communication with the user, the bigwig is empty and not working in IGV.
