### ISSUE TITLE
Bigwig issue

### ISSUE THREAD

**Issue by joachimwolff** [deeptools/pyGenomeTracks#381]
It might be bigwigs crash if you select a region size larger the chromosome actually is.

```
INFO:pygenometracks.tracksClass:plotting 10. [RNA E10.5]
WARNING:pygenometracks.tracks.GenomeTrack:error found while reading bigwig scores (Invalid interval bounds!).
Trying again. Iter num: 1.

WARNING:pygenometracks.tracks.GenomeTrack:error found while reading bigwig scores (Invalid interval bounds!).
Trying again. Iter num: 2.

WARNING:pygenometracks.tracks.GenomeTrack:error found while reading bigwig scores (Invalid interval bounds!).
Trying again. Iter num: 3.

WARNING:pygenometracks.tracks.GenomeTrack:error found while reading bigwig scores (Invalid interval bounds!).
Trying again. Iter num: 4.

WARNING:pygenometracks.tracks.GenomeTrack:error found while reading bigwig scores (Invalid interval bounds!).
Trying again. Iter num: 5.

Traceback (most recent call last):
  File "/tungstenfs/scratch/grijli/wolfjoac/miniconda3/envs/hicexplorer_dev/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "/tungstenfs/scratch/grijli/wolfjoac/miniconda3/envs/hicexplorer_dev/lib/python3.8/site-packages/pygenometracks/plotTracks.py", line 335, in main
    trp.plot(file_name, chrom, start, end, title=args.title,
  File "/tungstenfs/scratch/grijli/wolfjoac/miniconda3/envs/hicexplorer_dev/lib/python3.8/site-packages/pygenometracks/tracksClass.py", line 272, in plot
    track.plot(plot_axis, chrom, start, end)
  File "/tungstenfs/scratch/grijli/wolfjoac/miniconda3/envs/hicexplorer_dev/lib/python3.8/site-packages/pygenometracks/tracks/BigWigTrack.py", line 264, in plot
    plot_coverage(ax, x_values, transformed_scores, self.plot_type,
  File "/tungstenfs/scratch/grijli/wolfjoac/miniconda3/envs/hicexplorer_dev/lib/python3.8/site-packages/pygenometracks/utilities.py", line 242, in plot_coverage
    ax.fill_between(x_values, score_list, linewidth=0.1,
  File "/tungstenfs/scratch/grijli/wolfjoac/miniconda3/envs/hicexplorer_dev/lib/python3.8/site-packages/matplotlib/__init__.py", line 1599, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/tungstenfs/scratch/grijli/wolfjoac/miniconda3/envs/hicexplorer_dev/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 5233, in fill_between
    y1 = ma.masked_invalid(self.convert_yunits(y1))
  File "/tungstenfs/scratch/grijli/wolfjoac/miniconda3/envs/hicexplorer_dev/lib/python3.8/site-packages/numpy/ma/core.py", line 2366, in masked_invalid
    condition = ~(np.isfinite(a))
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by lldelisle** [comment]
Solved in version 3.7
