### ISSUE TITLE
bed line limitation or truncation

### ISSUE THREAD

**Issue by jakewendt** [deeptools/pyGenomeTracks#403]
I just started using pyGenomeTracks to generate some images. It has worked for all of my samples, except one. 2 of the bed files have rather long lines which appear to be being truncated during the reading process, and it fails on each if I comment the first. Below are the version, command, error and the bed file contents. The first truncation occurred at a comma leading me to believe that there may be a limit to the number of blocks. The last truncation occurs in the middle of a number which changes things and leads me to believe that there is a limitation to line length or something similar. I'm still digging.

Regardless, any help would be appreciated.

```
python --version
Python 3.8.13

pyGenomeTracks --version
pyGenomeTracks 3.7
```

This is the error when the first bed file is read from the ini file.

```
pyGenomeTracks --tracks out/NC_001798.2.ini --region NC_001798.2:0-16000 --trackLabelFraction 0.2 --width 38 --dpi 130 -o NC_001798.2.png
INFO:pygenometracks.tracksClass:initialize 1. [spacer]
INFO:pygenometracks.tracksClass:initialize 2. [x-axis]
INFO:pygenometracks.tracksClass:initialize 3. [spacer]
INFO:pygenometracks.tracksClass:initialize 4. [RM]
  0%|                                                                                                                                       | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/jake/.python/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "/Users/jake/Library/Python/3.8/lib/python/site-packages/pygenometracks/plotTracks.py", line 274, in main
    trp = PlotTracks(args.tracks.name, args.width, fig_height=args.height,
  File "/Users/jake/Library/Python/3.8/lib/python/site-packages/pygenometracks/tracksClass.py", line 108, in __init__
    self.track_obj_list.append(track_class(properties))
  File "/Users/jake/Library/Python/3.8/lib/python/site-packages/pygenometracks/tracks/BedTrack.py", line 187, in __init__
    self.interval_tree, min_score, max_score = self.process_bed(self.properties['region'])
  File "/Users/jake/Library/Python/3.8/lib/python/site-packages/pygenometracks/tracks/BedTrack.py", line 288, in process_bed
    for bed in tqdm(bed_file_h, total=total_length):
  File "/Users/jake/Library/Python/3.8/lib/python/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/Users/jake/Library/Python/3.8/lib/python/site-packages/pygenometracks/readBed.py", line 80, in __next__
    bed = self.get_bed_interval(line)
  File "/Users/jake/Library/Python/3.8/lib/python/site-packages/pygenometracks/readBed.py", line 312, in get_bed_interval
    check_bed12(line_values, self.line_number, bed_line)
  File "/Users/jake/Library/Python/3.8/lib/python/site-packages/pygenometracks/readBed.py", line 337, in check_bed12
    assert len(block_relative_starts) == block_counts, \
AssertionError: The number of blocks: 116 does not correspond tothe number of blocks relative starts: [0, 154, 388, 658, 1244, 1318, 2434, 3299, 3868, 4914, 5466, 5701, 6163, 6261, 6299, 6404, 6523, 6819, 7228, 7643, 8281, 8496, 8659, 8776, 8848, 9276, 15298, 17206, 18294, 18854, 19715, 20861, 21941, 24216, 26030, 26858, 31807, 32928, 34913, 42878, 43911, 48793, 50836, 51949, 53254, 53650, 53973, 54498, 55978, 58628, 58974, 62658, 62857, 63224, 65276, 68564, 68840, 72543, 72664, 73845, 75835, 76082, 78391, 85026, 85181, 92834, 98515, 99827, 101576, 102729, 104276, 106080, 115157, 118407, 118631, 118759, 118975, 119133, 119243, 119858, 120014, 120109, 120456, 120851, 120974, 121036, 121071, 121454, 121568, 121784, 122345, 122523, 122812, 123391, 125948, 126033, 126622, 126772, 127120, 130582, 131530, 131583, 132017, 132131, 132340]
line #2:
NC_001798.2	1	309350	.	0	+	0	0	0	116	0,46,161,41,44,55,52,33,62,53,71,52,78,24,48,63,65,46,37,73,26,66,31,33,66,48,45,35,28,27,21,60,35,42,40,41,35,46,34,57,39,46,25,26,33,47,41,39,42,28,50,28,29,49,80,79,46,63,36,56,52,55,33,38,36,46,27,75,53,67,35,122,71,66,79,66,76,83,62,96,79,63,46,66,48,24,87,42,51,71,63,149,58,62,55,44,41,161,50,44,49,36,69,18,24,81,24,27,42,24,24,18,69,103,46,0,	0,154,388,658,1244,1318,2434,3299,3868,4914,5466,5701,6163,6261,6299,6404,6523,6819,7228,7643,8281,8496,8659,8776,8848,9276,15298,17206,18294,18854,19715,20861,21941,24216,26030,26858,31807,32928,34913,42878,43911,48793,50836,51949,53254,53650,53973,54498,55978,58628,58974,62658,62857,63224,65276,68564,68840,72543,72664,73845,75835,76082,78391,85026,85181,92834,98515,99827,101576,102729,104276,106080,115157,118407,118631,118759,118975,119133,119243,119858,120014,120109,120456,120851,120974,121036,121071,121454,121568,121784,122345,122523,122812,123391,125948,126033,126622,126772,127120,130582,131530,131583,132017,132131,132340
```

And this is the first bed file contents.

```
cat 20211122-Homology-Paper/masks/NC_001798.2.masked.fasta.bed

NC_001798.2	1	309350	.	0	+	0	0	0	116	0,46,161,41,44,55,52,33,62,53,71,52,78,24,48,63,65,46,37,73,26,66,31,33,66,48,45,35,28,27,21,60,35,42,40,41,35,46,34,57,39,46,25,26,33,47,41,39,42,28,50,28,29,49,80,79,46,63,36,56,52,55,33,38,36,46,27,75,53,67,35,122,71,66,79,66,76,83,62,96,79,63,46,66,48,24,87,42,51,71,63,149,58,62,55,44,41,161,50,44,49,36,69,18,24,81,24,27,42,24,24,18,69,103,46,0,	0,154,388,658,1244,1318,2434,3299,3868,4914,5466,5701,6163,6261,6299,6404,6523,6819,7228,7643,8281,8496,8659,8776,8848,9276,15298,17206,18294,18854,19715,20861,21941,24216,26030,26858,31807,32928,34913,42878,43911,48793,50836,51949,53254,53650,53973,54498,55978,58628,58974,62658,62857,63224,65276,68564,68840,72543,72664,73845,75835,76082,78391,85026,85181,92834,98515,99827,101576,102729,104276,106080,115157,118407,118631,118759,118975,119133,119243,119858,120014,120109,120456,120851,120974,121036,121071,121454,121568,121784,122345,122523,122812,123391,125948,126033,126622,126772,127120,130582,131530,131583,132017,132131,132340,132424,133217,144345,145823,148501,149378,149593,149656,150123,154575,309349,
```

This is the error when the second bed file is read from the ini file. (after I commented out the first)

```
pyGenomeTracks --tracks out/NC_001798.2.ini --region NC_001798.2:0-16000 --trackLabelFraction 0.2 --width 38 --dpi 130 -o NC_001798.2.png
INFO:pygenometracks.tracksClass:initialize 1. [spacer]
INFO:pygenometracks.tracksClass:initialize 2. [x-axis]
INFO:pygenometracks.tracksClass:initialize 3. [spacer]
INFO:pygenometracks.tracksClass:initialize 4. [RM HM]
  0%|                                                                                                                                       | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/jake/.python/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "/Users/jake/Library/Python/3.8/lib/python/site-packages/pygenometracks/plotTracks.py", line 274, in main
    trp = PlotTracks(args.tracks.name, args.width, fig_height=args.height,
  File "/Users/jake/Library/Python/3.8/lib/python/site-packages/pygenometracks/tracksClass.py", line 108, in __init__
    self.track_obj_list.append(track_class(properties))
  File "/Users/jake/Library/Python/3.8/lib/python/site-packages/pygenometracks/tracks/BedTrack.py", line 187, in __init__
    self.interval_tree, min_score, max_score = self.process_bed(self.properties['region'])
  File "/Users/jake/Library/Python/3.8/lib/python/site-packages/pygenometracks/tracks/BedTrack.py", line 288, in process_bed
    for bed in tqdm(bed_file_h, total=total_length):
  File "/Users/jake/Library/Python/3.8/lib/python/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/Users/jake/Library/Python/3.8/lib/python/site-packages/pygenometracks/readBed.py", line 80, in __next__
    bed = self.get_bed_interval(line)
  File "/Users/jake/Library/Python/3.8/lib/python/site-packages/pygenometracks/readBed.py", line 312, in get_bed_interval
    check_bed12(line_values, self.line_number, bed_line)
  File "/Users/jake/Library/Python/3.8/lib/python/site-packages/pygenometracks/readBed.py", line 337, in check_bed12
    assert len(block_relative_starts) == block_counts, \
AssertionError: The number of blocks: 129 does not correspond tothe number of blocks relative starts: [0, 154, 388, 658, 1244, 1318, 2434, 3299, 3868, 4625, 4914, 5466, 5701, 6163, 6261, 6299, 6404, 6523, 6819, 7228, 7643, 8281, 8496, 8659, 8776, 8848, 9075, 9276, 15298, 17206, 18294, 18854, 19715, 20861, 21941, 24216, 24700, 26030, 26858, 31807, 32928, 34913, 42878, 43911, 48793, 50836, 51949, 53254, 53650, 53973, 54498, 55978, 58628, 58974, 62658, 62857, 63224, 65276, 68564, 68840, 72543, 72664, 73845, 75835, 76082, 78391, 85026, 85181, 92834, 98515, 99827, 101576, 102729, 104276, 106080, 115157, 118100, 118407, 118631, 118759, 118975, 119133, 119243, 119858, 120014, 120109, 120456, 120851, 120974, 121036, 121071, 121454, 121568, 121784, 122345, 122523, 122812, 123391, 125948, 1260]
line #2:
NC_001798.2	1	309350	.	0	+	0	0	0	129	0,46,161,41,44,55,52,33,62,176,53,71,52,78,24,48,63,65,46,37,73,26,66,31,33,66,151,48,45,35,28,27,21,60,35,42,51,40,41,35,46,34,57,39,46,25,26,33,47,41,39,42,28,50,28,29,49,80,79,46,63,36,56,52,55,33,38,36,46,27,75,53,67,35,122,71,126,66,79,66,76,83,62,96,79,63,46,66,48,24,87,42,51,71,63,149,58,62,55,44,41,161,50,44,76,76,49,36,69,18,24,81,24,51,51,27,42,51,51,76,24,24,18,69,103,51,51,46,0,	0,154,388,658,1244,1318,2434,3299,3868,4625,4914,5466,5701,6163,6261,6299,6404,6523,6819,7228,7643,8281,8496,8659,8776,8848,9075,9276,15298,17206,18294,18854,19715,20861,21941,24216,24700,26030,26858,31807,32928,34913,42878,43911,48793,50836,51949,53254,53650,53973,54498,55978,58628,58974,62658,62857,63224,65276,68564,68840,72543,72664,73845,75835,76082,78391,85026,85181,92834,98515,99827,101576,102729,104276,106080,115157,118100,118407,118631,118759,118975,119133,119243,119858,120014,120109,120456,120851,120974,121036,121071,121454,121568,121784,122345,122523,122812,123391,125948,1260
```

And this is the second bed file contents.

```
cat 20211122-Homology-Paper/split.vsl/NC_001798.2.masked.split.25.mask.fasta.bed

NC_001798.2	1	309350	.	0	+	0	0	0	129	0,46,161,41,44,55,52,33,62,176,53,71,52,78,24,48,63,65,46,37,73,26,66,31,33,66,151,48,45,35,28,27,21,60,35,42,51,40,41,35,46,34,57,39,46,25,26,33,47,41,39,42,28,50,28,29,49,80,79,46,63,36,56,52,55,33,38,36,46,27,75,53,67,35,122,71,126,66,79,66,76,83,62,96,79,63,46,66,48,24,87,42,51,71,63,149,58,62,55,44,41,161,50,44,76,76,49,36,69,18,24,81,24,51,51,27,42,51,51,76,24,24,18,69,103,51,51,46,0,	0,154,388,658,1244,1318,2434,3299,3868,4625,4914,5466,5701,6163,6261,6299,6404,6523,6819,7228,7643,8281,8496,8659,8776,8848,9075,9276,15298,17206,18294,18854,19715,20861,21941,24216,24700,26030,26858,31807,32928,34913,42878,43911,48793,50836,51949,53254,53650,53973,54498,55978,58628,58974,62658,62857,63224,65276,68564,68840,72543,72664,73845,75835,76082,78391,85026,85181,92834,98515,99827,101576,102729,104276,106080,115157,118100,118407,118631,118759,118975,119133,119243,119858,120014,120109,120456,120851,120974,121036,121071,121454,121568,121784,122345,122523,122812,123391,125948,126033,126622,126772,127120,130582,131325,131425,131530,131583,132017,132131,132340,132424,133217,133400,133525,144345,145823,146225,148200,148275,148501,149378,149593,149656,150123,150250,150350,154575,309349,
```

**Comment by lldelisle** [comment]
Hi,
I am really sorry for that. This is due to a flaw in bedtools intersect we are using (https://github.com/arq5x/bedtools2/issues/973).
I think if you downgrade bedtools it fixes the issue. I am on my phone so I don't know which version but ping me on Monday if you don't fix it.

**Comment by jakewendt** [comment]
Thank you for the quick reply. I'll look at it again tomorrow morning.

**Comment by jakewendt** [comment]
Currently I'm using 

```
bedtools --version
bedtools v2.30.0
```

**Comment by jakewendt** [comment]
The error goes away if I uninstall bedtools completely.

**Comment by jakewendt** [comment]
`bedtools v2.29.0` works

**Comment by lldelisle** [comment]
Indeed, this is what I had in mind. In theory, pyGenomeTracks can work without bedtools but if you have it, it speeds up as it will intersect all beds with the region to plot before processing them.

**Comment by jakewendt** [comment]
Thank you.
