### ISSUE TITLE
Support for mcool files with hic_matrix_square

### ISSUE THREAD

**Issue by mxw010** [deeptools/pyGenomeTracks#404]
**Welcome to the pyGenomeTracks GitHub repository! Before opening the issue please check
 that the following requirements are met :**

  - [ x ] Search whether this issue (or a similar issue) has been solved before
  using the search tab above. Link the previous issue if appropriate below.

  - [ x ] Paste your pyGenomeTracks version (`pyGenomeTracks --version`) and your python
  version (`python --version`) below.

```
pyGenomeTracks --version
pyGenomeTracks 3.7

python --version
Python 3.9.12
```

Pretty sure this is due to the lack of support for .mcool file for some reason, because when I have 

```
[hic matrix]
file = path-to-mcool.mcool::/resolutions/50000
```

in the .ini file I get 

```pyGenomeTracks --tracks test.ini --region chr2:222000000-223000000 -o tads_square.pdf
Traceback (most recent call last):
  File "~/.conda/envs/hicexplorer/lib/python3.9/site-packages/pygenometracks/tracksClass.py", line 677, in check_file_exists
    open(file_name_to_check, 'r').close()
FileNotFoundError: [Errno 2] No such file or directory: '~/path-to-file.mcool::/resolutions/50000'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.conda/envs/hicexplorer/lib/python3.9/site-packages/pygenometracks/tracksClass.py", line 685, in check_file_exists
    open(name_with_tracks_path_to_check, 'r').close()
FileNotFoundError: [Errno 2] No such file or directory: '/~/path-to-file.mcool::/resolutions/50000'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.conda/envs/hicexplorer/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "~/.conda/envs/hicexplorer/lib/python3.9/site-packages/pygenometracks/plotTracks.py", line 274, in main
    trp = PlotTracks(args.tracks.name, args.width, fig_height=args.height,
  File "~/.conda/envs/hicexplorer/lib/python3.9/site-packages/pygenometracks/tracksClass.py", line 80, in __init__
    self.parse_tracks(tracks_file, plot_regions=plot_regions)
  File "~/.conda/envs/hicexplorer/lib/python3.9/site-packages/pygenometracks/tracksClass.py", line 604, in parse_tracks
    track_options = self.check_file_exists(track_options,
  File "~/.conda/envs/hicexplorer/lib/python3.9/site-packages/pygenometracks/tracksClass.py", line 688, in check_file_exists
    raise InputError(f"File in section [{track_dict['section_name']}] "
pygenometracks.utilities.InputError: File in section [3. [hic matrix]] not found:
~/path-to-file.mcool::/resolutions/50000

```

If I just feed the path to mcool, of course cooler complains that I didn't specify a group. 

but when i change the file path to a .cool file, it plots nicely. hic_matrix already supports .mcool file so I would assume the code is already in place somewhere.

**Comment by lldelisle** [comment]
Hi,
I am sorry. When I implemented the squared matrix I forgot to change this line:
https://github.com/deeptools/pyGenomeTracks/blob/c42e74e725d22269c33718d9f5df11e0c45c7378/pygenometracks/tracksClass.py#L606
I'll make a PR which corrects it later today.

**Comment by mxw010** [comment]
Thanks! I Appreciate the quick response.

**Comment by lldelisle** [comment]
I nearly forgot you. The PR is ready. I need to check with my colleagues if we do a quick bug fix release.

**Comment by lldelisle** [comment]
Hi,
This is really strange because we have a test for this:
https://github.com/deeptools/pyGenomeTracks/blob/b8918d43b0bd1ca9dd2939fdd0d93a5a297d0453/pygenometracks/tests/test_hiCMatrixSquareTracks.py#L289-L305
The ini file is here: https://github.com/deeptools/pyGenomeTracks/blob/b8918d43b0bd1ca9dd2939fdd0d93a5a297d0453/pygenometracks/tests/test_hiCMatrixSquareTracks.py#L137-L162
And it passes.
Could you try to repeat this on your mcool file to be sure the way you specify the resolution is the good one?
```
$ cooler info matrix.mcool
Traceback (most recent call last):
  File "/home/ldelisle/.conda/envs/lastVersion/bin/cooler", line 10, in <module>
    sys.exit(cli())
  File "/home/ldelisle/.conda/envs/lastVersion/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ldelisle/.conda/envs/lastVersion/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ldelisle/.conda/envs/lastVersion/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ldelisle/.conda/envs/lastVersion/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ldelisle/.conda/envs/lastVersion/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ldelisle/.conda/envs/lastVersion/lib/python3.9/site-packages/cooler/cli/_util.py", line 203, in decorated
    func(*args, **kwargs)
  File "/home/ldelisle/.conda/envs/lastVersion/lib/python3.9/site-packages/cooler/cli/info.py", line 41, in info
    c = Cooler(cool_uri)
  File "/home/ldelisle/.conda/envs/lastVersion/lib/python3.9/site-packages/cooler/api.py", line 85, in __init__
    self._refresh()
  File "/home/ldelisle/.conda/envs/lastVersion/lib/python3.9/site-packages/cooler/api.py", line 106, in _refresh
    raise KeyError(err_msg) from None
KeyError: "No cooler found at: matrix.mcool. Coolers found in ['/0', '/1', '/2', '/3', '/4']. Use '::' to specify a group path"
$ cooler info matrix.mcool::/0
{
    "bin-size": 640000,
    "bin-type": "fixed",
    "creation-date": "2018-02-14T15:11:28.401416",
    "format": "HDF5::Cooler",
    "format-url": "https://github.com/mirnylab/cooler",
    "format-version": 2,
    "generated-by": "cooler-0.7.6",
    "genome-assembly": "unknown",
    "nbins": 209,
    "nchroms": 5,
    "nnz": 21798,
    "sum": 2329145
}

```

**Comment by TincaSubic** [comment]
Thanks for a fast reply! The issue was pretty simple - I relied on building
a .ini file using make_tracks_file. If I construct the ini file manually
and use the above test with my mcool files, then everything works fine.
Thanks!
