### ISSUE TITLE
plot several bigwig with error "'BigWigTrack' object has no attribute 'bw2'"

### ISSUE THREAD

**Issue by jiangshan529** [deeptools/pyGenomeTracks#421]
Hello, I am trying to plot two bigwig tracks together using pyGenomeTracks. However, it comes out with such error when plotting the second track:

INFO:pygenometracks.tracksClass:initialize 6. [test bigwig]
INFO:pygenometracks.tracksClass:initialize 7. [test bigwig log]
[bwOpen] bwg->idx is NULL bwg->hdr->dataOffset 0x29a!
[pyBwOpen] bw is NULL!
Traceback (most recent call last):
  File "/home/baijsh/biosoft/yes/envs/hicexplorer36/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "/home/baijsh/biosoft/yes/envs/hicexplorer36/lib/python3.8/site-packages/pygenometracks/plotTracks.py", line 318, in main
    trp = PlotTracks(args.tracks.name, args.width, fig_height=args.height,
  File "/home/baijsh/biosoft/yes/envs/hicexplorer36/lib/python3.8/site-packages/pygenometracks/tracksClass.py", line 109, in __init__
    self.track_obj_list.append(track_class(properties))
  File "/home/baijsh/biosoft/yes/envs/hicexplorer36/lib/python3.8/site-packages/pygenometracks/tracks/BigWigTrack.py", line 116, in __init__
    self.bw = pyBigWig.open(self.properties['file'])
RuntimeError: Received an error during file opening!
Exception ignored in: <function BigWigTrack.__del__ at 0x7f0e32e13940>
Traceback (most recent call last):
  File "/home/baijsh/biosoft/yes/envs/hicexplorer36/lib/python3.8/site-packages/pygenometracks/tracks/BigWigTrack.py", line 287, in __del__
    if self.bw2 is not None:
AttributeError: 'BigWigTrack' object has no attribute 'bw2'

**Comment by lldelisle** [comment]
Hi,
I would say that the bigwig you are trying to plot (in section [test bigwig log]) is corrupted or is not a bigwig.
Can you check the size of the file? If you downloaded it from somewhere can you try to redownload it?

**Comment by lldelisle** [comment]
Feel free to reopen if it is not solved.
