### ISSUE TITLE
numpy issues

### ISSUE THREAD

**Issue by scriscio** [deeptools/pyGenomeTracks#43]
Hi, I followed install instructions for conda, but I am getting an error which looks numpy related:
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
Traceback (most recent call last):
  File "/home/kqwt693/.conda/envs/pygenometracks/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "/home/kqwt693/.conda/envs/pygenometracks/lib/python3.6/site-packages/pygenometracks/plotTracks.py", line 278, in main
    track_label_width=args.trackLabelFraction)
  File "/home/kqwt693/.conda/envs/pygenometracks/lib/python3.6/site-packages/pygenometracks/tracksClass.py", line 119, in __init__
    self.track_obj_list.append(track_class(properties))
  File "/home/kqwt693/.conda/envs/pygenometracks/lib/python3.6/site-packages/pygenometracks/tracksClass.py", line 745, in __init__
    import pyBigWig
ImportError: numpy.core.multiarray failed to import

Any advice on how to resolve this error?

**Comment by scriscio** [comment]
The issue was solved by installing dependency separately for pybigwig
conda install pybigwig -c bioconda
