### ISSUE TITLE
getting "ImportError: cannot import name typeDict" error 

### ISSUE THREAD

**Issue by yonniejon** [deeptools/pyGenomeTracks#453]
**Welcome to the pyGenomeTracks GitHub repository! Before opening the issue please check
 that the following requirements are met :**

  - [x] Search whether this issue (or a similar issue) has been solved before
  using the search tab above. Link the previous issue if appropriate below.

  - [x] Paste your pyGenomeTracks version (`pyGenomeTracks --version`) and your python
  version (`python --version`) below.
I used pip for the installation and received message
`Successfully installed pyGenomeTracks-3.8 `
my python version is `Python 3.9.2`.

  - [x] Paste the full pyGenomeTracks command that produces the issue below
  (ignore if you simply spotted the issue in the code/documentation).
running the command `pyGenomeTracks` with no options causes the error.

  - [x] Paste the output printed on screen from the command that produces the issue
  below (ignore if you simply spotted the issue in the code/documentation).
The output of running the command is:

```
Traceback (most recent call last):
  File "/cs/usr/jrosensk/.local/bin/pyGenomeTracks", line 4, in <module>
    from pygenometracks.plotTracks import main
  File "/cs/usr/jrosensk/.local/lib/python3.9/site-packages/pygenometracks/plotTracks.py", line 149, in <module>
    from pygenometracks.tracksClass import PlotTracks
  File "/cs/usr/jrosensk/.local/lib/python3.9/site-packages/pygenometracks/tracksClass.py", line 18, in <module>
    from pygenometracks.tracks.GenomeTrack import GenomeTrack
  File "/cs/usr/jrosensk/.local/lib/python3.9/site-packages/pygenometracks/tracks/__init__.py", line 7, in <module>
    mod = __import__('.'.join([__name__, py]), fromlist=[py])
  File "/cs/usr/jrosensk/.local/lib/python3.9/site-packages/pygenometracks/tracks/HiCMatrixTrack.py", line 4, in <module>
    from . HiCMatrixLikeTrack import HiCMatrixLikeTrack
  File "/cs/usr/jrosensk/.local/lib/python3.9/site-packages/pygenometracks/tracks/HiCMatrixLikeTrack.py", line 1, in <module>
    from hicmatrix import HiCMatrix
  File "/cs/usr/jrosensk/.local/lib/python3.9/site-packages/hicmatrix/HiCMatrix.py", line 12, in <module>
    import tables
  File "/usr/lib/python3/dist-packages/tables/__init__.py", line 99, in <module>
    from .utilsextension import (
  File "tables/utilsextension.pyx", line 169, in init tables.utilsextension
ImportError: cannot import name typeDict
```

I assume this is because of some package having an unexpected version. I guess the code should check for python version and then use the correct import statement?

**Comment by lldelisle** [comment]
Hi,
Sorry for the late answer. I am sorry. I don´t know where it comes from but something is strange in your error message:
```
 File "tables/utilsextension.pyx", line 169, in init tables.utilsextension
```
Do you have such a file? Would you mind to remove it and try again?

Also it seems that it is using the native `tables` (`/usr/lib`) while other dependencies come from pip `/cs/usr/jrosensk/.local/`...

I don't know very well pip and I always use conda see https://pygenometracks.readthedocs.io/en/latest/content/installation.html#command-line-installation-using-conda-and-mamba

**Comment by lldelisle** [comment]
Please feel free to reopen the issue if you still cannot use pyGenomeTracks
