### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'float'

### ISSUE THREAD

**Issue by sarah872** [deeptools/pyGenomeTracks#58]
I want to plot a bam file together with a gff file.

I therefore converted the bam + gff file to bed-files (bed6). Please see the input files below:

```
bedtools bamtobed -i file.bam >bam.bed
gff2bed <saccharomyces_cerevisiae_mod.gff | cut -f 1-6 >gff.bed
```

Then I run `pyGenomeTracks`:

```
make_tracks_file -f gff.bed bam.bed -o tracks.ini
pyGenomeTracks --tracks tracks.ini --region chrI:10090-13000 --outFileName nice_image.pdf
```

But I am getting the following error:

```
Traceback (most recent call last):
  File "/home/user/viehboeck/.conda/envs/pygenometracks/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "/home/user/viehboeck/.conda/envs/pygenometracks/lib/python3.6/site-packages/pygenometracks/plotTracks.py", line 303, in main
    track_label_width=args.trackLabelFraction, pRegion=region)
  File "/home/user/viehboeck/.conda/envs/pygenometracks/lib/python3.6/site-packages/pygenometracks/tracksClass.py", line 107, in __init__
    self.track_obj_list.append(track_class(properties))
  File "/home/user/viehboeck/.conda/envs/pygenometracks/lib/python3.6/site-packages/pygenometracks/tracks/BedTrack.py", line 114, in __init__
    self.interval_tree, min_score, max_score = self.process_bed()
  File "/home/user/viehboeck/.conda/envs/pygenometracks/lib/python3.6/site-packages/pygenometracks/tracks/BedTrack.py", line 162, in process_bed
    if bed.score < min_score:
TypeError: '<' not supported between instances of 'str' and 'float'
```

[files.zip](https://github.com/deeptools/pyGenomeTracks/files/2775568/files.zip)

**Comment by bgruening** [comment]
@sarah872 try to reformat your BED file, so that the score column in a value floating point value.

**Comment by sarah872** [comment]
The reason why the error popped up was because the `gff2bed` doesn't write a score. So I manually changed the `.` in  column 5 into a number. Now it works!
