### ISSUE TITLE
errors when using --BED for <200kb regions

### ISSUE THREAD

**Issue by bakerwm** [deeptools/pyGenomeTracks#63]
using `--BED` argument,
line: 297-299 in file `pyGenomeTracks/pygenometracks/plotTracks.py`

```
if end - start < 200000:
    start -= 100000
    end += 100000
```

If the region is shorter than 200kb and starts before 100kb on chromosome, or the chromosome is shorter than 100kb. the program will fail.

the output:
```
$ head demo.bed
chr1    1    7480

$ pyGenomeTracks --tracks track.demo.ini --BED demo.bed -o aaaaaa
INFO:pygenometracks.tracksClass:time initializing track(s):
INFO:pygenometracks.tracksClass:0.004621744155883789
saving _chr1-1-7480.aaaaaa
chr1 -99999 107480
DEBUG:pygenometracks.tracksClass:Figure size in cm is 40 x 14.0. Dpi is set to 72

INFO:pygenometracks.tracksClass:plotting 1. [x-axis]
/home/wangming/anaconda3/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning:
Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
INFO:pygenometracks.tracksClass:plotting 2. [spacer]
INFO:pygenometracks.tracksClass:plotting 3. [a.fwd]
WARNING:pygenometracks.tracks.GenomeTrack:error found while reading bigwig scores (Invalid interval bounds!).
Trying again. Iter num: 1
WARNING:pygenometracks.tracks.GenomeTrack:error found while reading bigwig scores (Invalid interval bounds!).
Trying again. Iter num: 2
WARNING:pygenometracks.tracks.GenomeTrack:error found while reading bigwig scores (Invalid interval bounds!).
Trying again. Iter num: 3
WARNING:pygenometracks.tracks.GenomeTrack:error found while reading bigwig scores (Invalid interval bounds!).
Trying again. Iter num: 4
WARNING:pygenometracks.tracks.GenomeTrack:error found while reading bigwig scores (Invalid interval bounds!).
Trying again. Iter num: 5
Traceback (most recent call last):
  File "/home/wangming/anaconda3/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "/home/wangming/.local/lib/python3.6/site-packages/pygenometracks/plotTracks.py", line 302, in main
    trp.plot(file_name, chrom, start, end, title=args.title)
  File "/home/wangming/.local/lib/python3.6/site-packages/pygenometracks/tracksClass.py", line 246, in plot
    track.plot(plot_axis, chrom, start, end)
  File "/home/wangming/.local/lib/python3.6/site-packages/pygenometracks/tracks/BigWigTrack.py", line 142, in plot
    facecolor=self.properties['color'], where=scores_per_bin >= 0, interpolate=True)
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

```

**Comment by LeilyR** [comment]
Hi, Thanks a lot for reporting that. That has been added by a colleague to avoid plotting TADs on very small regions. I removed it and replaced it with a stderr message. You can already find it under the develop branch.
